# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Altibonne
                                 A QGIS plugin
 Gestion des profils
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-01-08
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Gérôme PECHEUR (IGN)
        email                : gerome.pecheur@ign.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os

from qgis.PyQt.QtCore import  QRegularExpression, QSettings, QPoint, QSize
from qgis.PyQt.QtGui import QPainterPath, QColor, QFont, QRegularExpressionValidator
from qgis.PyQt.QtWidgets import QGraphicsPathItem, QGraphicsTextItem, QApplication, QGraphicsItem
from qgis.PyQt.uic import loadUi

from qgis.PyQt.QtWidgets import QGraphicsScene, QGraphicsView,QGraphicsRectItem
from qgis.core import QgsGeometry, QgsWkbTypes, QgsPoint,QgsApplication

# Import the code for the dialog
from .altibonne_dialog import AltibonneDialog
from .fonction import *
from .constante import *
from .clic_cercle import *
from .mapping_version import *

def fusion_points(l1, l2):
    return l1 + l2

# fonction pour orienter 2 lignes
def orienter_deux_lignes(layer, sommets_l1, sommets_l2):
    p1_start, p1_end = sommets_l1[0], sommets_l1[-1]
    p2_start, p2_end = sommets_l2[0], sommets_l2[-1]

    # Comparer seulement les x et les y
    if points_egau_xy(layer,p1_end, p2_start, TOLERANCE_PT_CONFONDU):
        # L1, L2 sans inversion
        return sommets_l1, sommets_l2
    elif points_egau_xy(layer,p1_end, p2_end, TOLERANCE_PT_CONFONDU):
        # L1, L2 inversée
        return sommets_l1, list(reversed(sommets_l2))
    elif points_egau_xy(layer,p1_start, p2_end, TOLERANCE_PT_CONFONDU):
        # L1 inversée, L2 inversés
        return list(reversed(sommets_l1)), list(reversed(sommets_l2))
    elif points_egau_xy(layer,p1_start, p2_start, TOLERANCE_PT_CONFONDU):
        # L1 inversée
        return list(reversed(sommets_l1)), sommets_l2
    # Pas de point commun sur les extrémités
    return None, None

# fonction pour faire un chainage de plus de 2 lignes
# IMPORTANT : self.layer.selectedFeatures() ne conserve pas l'ordre de sélection
# donc avant de faire le chainage, il faut determiner une extrémité
#  et une ligne qui un pt (debut ou fin) qui est commun avec aucunes autre ligne
def chainer_lignes(layer,features):
    # list_all_sommets : une liste de listes de sommets
    list_all_sommets = [list(f.geometry().vertices()) for f in features]

    # savoir quelle liste correspondant à une extremité
    indice = trouve_extremite(layer,list_all_sommets)
    # -1 --> un carrefour a été detecté
    if indice == -1:
        return -1

    if indice is None:
        return None
    else:
        # recuperation de la premiere ligne et suppression dans la liste totale
        ligne_enchaine = [list_all_sommets.pop(indice)]

    while list_all_sommets:
        trouve = False
        for i, sommets in enumerate(list_all_sommets):
            l1, l2 = orienter_deux_lignes(layer, ligne_enchaine[-1], sommets)
            if l1 is not None and l2 is not None:
                # IMPORTANT : on remplace la dernière ligne par sa version orientée
                ligne_enchaine[-1] = l1
                ligne_enchaine.append(l2)
                list_all_sommets.pop(i)
                trouve = True
                break
        if not trouve:
            return None
    return ligne_enchaine

def trouve_extremite(layer,list_all_sommets):
    # connexion est une liste qui contient, pour chaque tronçon sélectionné,
    # le nombre d'autres tronçons auxquels il est relié par une de ses extrémités.
    extremites = []
    for ligne in list_all_sommets:
        for pt in (ligne[0], ligne[-1]):
            trouve = False
            for i, (p, nb) in enumerate(extremites):
                if points_egau_xy(layer, pt, p, TOLERANCE_PT_CONFONDU):
                    extremites[i] = (p, nb + 1)
                    trouve = True
                    break
            if not trouve:
                extremites.append((pt, 1))

    # Une extrémité = une seule connexion
    # Retourner l'indice de la liste dont un point n'est pas en commun avec points des autres lignes.
    # On s'arrête a la premiere liste qui correspond
    # donc ça peut etre une des 2 extrémités

    # recherche dans connexions si j'ai des valeurs egal ou supérieur à 3
    # → au moins 3 tronçons partagent le meme points (carrefour)
    # on ne gère pas le profil pour ces cas.
    for pt,nb in extremites:
        if nb >= 3:
            return -1


    # dès qu'on trouve une connexion = 1
    # → on a trouvé une extrémité doc, on quitte, peu importe si c'est le premier tronçon ou le dernier
    for pt,nb in extremites:
        if nb == 1:
            for i, ligne in enumerate(list_all_sommets):
                if (points_egau_xy(layer, pt, ligne[0], TOLERANCE_PT_CONFONDU) or
                        points_egau_xy(layer, pt, ligne[-1], TOLERANCE_PT_CONFONDU)):
                    return i
    return None


# TEST
def affiche_only_z(list_point):
    alt = []
    for point in list_point:
        alt.append(point.z())
    print(alt)


# le z peut être different pour que 2 tronçons soient contigües
def points_egau_xy(layer,p1, p2, tol_metre):
    """Compare deux points en coordonnées réelles avec tolérance en mètres"""
    d = QgsDistanceArea()
    d.setSourceCrs(layer.crs(), QgsProject.instance().transformContext())
    if layer.crs().isGeographic():
        d.setEllipsoid(layer.crs().ellipsoidAcronym())
    distance = d.measureLine(QgsPointXY(p1.x(), p1.y()), QgsPointXY(p2.x(), p2.y()))
    return distance <= tol_metre

def is_projet_load():
    project = QgsProject.instance()
    if not project.fileName():
        QMessageBox.warning(None, "Avertissement", "Veuillez charger un projet")
        return False
    return True


# ============================================
class Altibonne:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        self.ligne_enchaine = None
        self.list_x = None
        self.list_y = None
        self.list_z = None
        self.last_mouse_pos = None
        self.dico_coord = {"x":[],"y":[],"z":[]}
        self.list_coord = []
        self.view = None
        self.line = None
        self.scene = None
        self.layer = None
        self.dlg = None
        self.seuil_pente = 0
        self.iface = iface
        self.point_clique = None
        self.texte_scene = None
        # liste des marqueurs pour "pointer" un point cliqué dans qgis
        self.liste_markers = []
        self.first_start = True


    # retourne les coordonnées de toute la sélection
    def get_coord_selection(self):
        self.dico_coord = {"x": [], "y": [], "z": []}
        features = self.layer.selectedFeatures()

        # Pas de sélection
        if len(features) == 0:
            return None

        # 1 de sélection
        elif len(features) == 1:
            self.ligne_enchaine = [list(features[0].geometry().vertices())]

        # 2 de sélections
        elif len(features) == 2:
            # récuperation de tous les sommets d'une geometrie
            sommets_l1 = list(features[0].geometry().vertices())
            sommets_l2 = list(features[1].geometry().vertices())
            self.ligne_enchaine = [sommets_l1, sommets_l2]

        # Plus de 2 sélections
        elif len(features) >2:
            self.ligne_enchaine = chainer_lignes(self.layer,features)
            if self.ligne_enchaine == -1:
                self.ecrire_dans_scene("Un carrefour a été détecté.")
                return None

            if self.ligne_enchaine is None:
                self.ecrire_dans_scene("Les tronçons ne sont pas contiguës.")
                return None

        self.dico_coord = {"x": [], "y": [], "z": []}
        for ligne in self.ligne_enchaine:
            for p in ligne:
                self.dico_coord["x"].append(p.x())
                self.dico_coord["y"].append(p.y())
                self.dico_coord["z"].append(p.z())

        return self.dico_coord

    def getZminmax_allselection(self):
        if self.dico_coord ["z"] == "":
            return None
        return min(self.dico_coord["z"]),max(self.dico_coord["z"])

    def actualiserSelection(self,reset_zoom = False):
        if reset_zoom:
            self.view.resetTransform()
        self.layer = self.iface.activeLayer()

        # Il faut réinitialiser avant tout
        self.point_clique = None
        self.list_coord = None


        if self.layer.selectedFeatureCount() == 0:
            self.ecrire_dans_scene("La sélection est vide")
            return

        # si layer sans z
        if not self.is_layer_valide():
            # QMessageBox.warning(self.dlg, "Avertissement",
            #                     f"La couche <span style = 'color:red'><b>{self.layer.name()}"
            #                     f" ({QgsWkbTypes.displayString(self.layer.wkbType())})</b></span> n'a pas de Z")
            texte = f"La couche : {self.layer.name()} n'a pas de Z"
            self.ecrire_dans_scene(texte)
            return

        # si autre chose que linéaire
        if not self.is_type_geom_valide():
            self.ecrire_dans_scene("La sélection doit être un linéaire")
            return

        if not self.dlg.isVisible():
            return
        self.scene.clear()

        self.dlg.label_nb_points.setText(f"Nb de points = {0}")
        self.dlg.label_warning.setText("")

        # suppression de tous les marqueurs (pointer le point cliqué) lorsque la selection change
        for m in self.liste_markers:
            self.iface.mapCanvas().scene().removeItem(m)
        self.liste_markers.clear()

        self.dlg.pushButtonUpDown.setEnabled(False)
        self.dlg.pushButtonChangeZpoint.setEnabled(False)

        self.dlg.lineEdit_valZ.setText("0")
        self.dlg.lineEditZpoint.setText("0")
        self.dlg.lineEditZInterpole.setText("0")
        self.dlg.label_warning.setText("")

        if self.layer.selectedFeatureCount() == 2:
            # self.dlg.pushButtonUpDown.setEnabled(True)
            selection = self.layer.selectedFeatures()
            sel1 = selection[0]
            sel2 = selection[1]
            if not sel1.geometry().touches(sel2.geometry()):
                self.ecrire_dans_scene("Les tronçons ne sont pas contiguës")
                # self.dlg.label_warning.setText(f"<span style = 'color:red'><b>Les tronçons ne sont pas contiguës</b></span>")
                return

        self.list_coord = self.get_coord_selection()
        if self.list_coord is None:
            return
        # on réinitialise le texte avant de redessiner un profil
        self.texte_scene = None
        # on reinitialise le zoom
        self.dessine_profil(self.list_coord)
        # → forcer le redimensionnement pour mettre à jour la scene
        self.dlg.resize(self.dlg.width()+1 , self.dlg.height()+1 )
        self.dlg.resize(self.dlg.width()-1 , self.dlg.height()-1 )


    def actualiser_seuil(self):
        self.seuil_pente = float(self.dlg.lineEdit_seuil_pente.text())
        self.actualiserSelection()

    def changeZpoint(self):
        if self.point_clique is None:
            return

        geom_type = self.layer.wkbType()
        geom_type_str = QgsWkbTypes.displayString(geom_type)
        if geom_type_str == "LineStringZ" or geom_type_str == "MultiLineStringZ":
            # Reprojeter point cliqué dans CRS de la couche,
            # car il est défini dans la class "CercleClickable" avec la projection du canvas !
            crs_canvas = self.iface.mapCanvas().mapSettings().destinationCrs()
            crs_layer = self.layer.crs()
            transform = QgsCoordinateTransform(crs_canvas, crs_layer, QgsProject.instance())
            pt_clique_layer = transform.transform(self.point_clique)

            self.layer.startEditing()
            # Parcourir les features sélectionnées
            for feat in self.layer.selectedFeatures():
                geom = feat.geometry()
                points = [QgsPoint(pt.x(), pt.y(), pt.z() if hasattr(pt, 'z') else 0)
                          for pt in geom.vertices()]

                # Chercher le point correspondant à point_xy
                for i, pt in enumerate(points):
                    if abs(pt.x() - pt_clique_layer.x()) < 1e-5 and abs(pt.y() - pt_clique_layer.y()) < 1e-5:
                        points[i] = QgsPoint(pt.x(), pt.y(), float(self.dlg.lineEditZInterpole.text()))  # Modifier seulement le Z
                        break

                # Recréer la géométrie et appliquer
                nouvelle_geom = QgsGeometry.fromPolyline(points)
                self.layer.changeGeometry(feat.id(), nouvelle_geom)

            # Rafraîchir la vue
            self.actualiserSelection(False)
        else:
            QMessageBox.warning(None, "Avertissement", "la sélection doit être un linéaire !")

    # test sur la saisie des linedit
    # lineedit  : linedit à tester
    # pushbutton : bouton associé pour gérer le setEnabled
    def is_saisie_valide(self,linedit,pushbutton):
        texte = linedit.text()
        if texte == "" or texte == "0":
            pushbutton.setEnabled(False)
        else:
            pushbutton.setEnabled(True)

        # cas particulier :
        # si aucun point n'est sélectionné → on masque le bouton de changement de z d'un point
        if not self.point_clique:
            self.dlg.pushButtonChangeZpoint.setEnabled(False)

    def is_layer_valide(self):
        # si layer sans z
        if not QgsWkbTypes.hasZ(self.layer.wkbType()):
            return False
        return True

    def is_type_geom_valide(self):
        # si autres chose que lineaire
        if (QgsWkbTypes.displayString(self.layer.wkbType()) != "LineStringZ"
                and QgsWkbTypes.displayString(self.layer.wkbType()) != "MultiLineStringZ"):
            return False
        return True

    def ecrire_dans_scene(self,texte):
        self.texte_scene = texte
        self.scene.clear()

        # force la scène à la taille visible actuelle
        self.scene.setSceneRect(0, 0, self.view.viewport().width(), self.view.viewport().height())

        txt = QGraphicsTextItem(texte)
        font = QFont("Arial", 15)
        font.setBold(True)
        txt.setFont(font)
        txt.setDefaultTextColor(QColor("red"))
        # taille du texte
        rect = txt.boundingRect()
        scene_rect = self.scene.sceneRect()
        x = scene_rect.center().x() - rect.width() / 2
        y = scene_rect.center().y() - rect.height() / 2
        txt.setPos(x, y)
        self.scene.addItem(txt)

    def changeZentite(self):
        if self.dlg.lineEdit_valZ.text() == "0" or self.dlg.lineEdit_valZ.text() == "":
            self.dlg.lineEdit_valZ.setText("0")
            return
        geom_type = self.layer.wkbType()
        geom_type_str = QgsWkbTypes.displayString(geom_type)
        if geom_type_str == "LineStringZ" or geom_type_str == "MultiLineString":
            self.layer.startEditing()
            for sel in self.layer.selectedFeatures():
                geometry = sel.geometry()
                new_points = []
                for point in geometry.vertices():
                    new_point = QgsPoint(point.x(), point.y(), point.z() + int(self.dlg.lineEdit_valZ.text()))
                    new_points.append(new_point)

                new_geometry = QgsGeometry.fromPolyline(new_points)
                self.layer.changeGeometry(sel.id(), new_geometry)
            self.actualiserSelection()
        else:
            QMessageBox.warning(None,"Avertissement","la sélection doit être un linéaire !")

    def distance_cumulee(self,d,list_x,list_y):
        distances_cumulees = [0]
        for i in range(1, len(list_x)):
            p1 = QgsPointXY(list_x[i - 1], list_y[i - 1])
            p2 = QgsPointXY(list_x[i], list_y[i])
            distance = d.measureLine(p1, p2)
            distances_cumulees.append(distances_cumulees[-1] + distance)
        return distances_cumulees

    def calcul_pente(self,d,pt1, pt2):
        # d = QgsDistanceArea()
        # d.setSourceCrs(self.layer.crs(), QgsProject.instance().transformContext())
        # if self.layer.crs().isGeographic():
        #     d.setEllipsoid(self.layer.crs().ellipsoidAcronym())
        distance = d.measureLine(QgsPointXY(pt1.x(), pt1.y()),QgsPointXY(pt2.x(), pt2.y()))
        if distance == 0:
            return None
        pente = (pt2.z() - pt1.z()) / distance
        pente_pourcent = pente * 100
        return pente_pourcent

    def dessine_gradations_z(self, zmin, zmax):
        """
        Dessine les graduations d'altitude sur la bordure gauche de la scène,
        par pas de 10 unités.
        """
        plage_disponible = self.scene.height() - MARGE_BAS - MARGE_HAUT

        # Arrondir zmin et zmax aux multiples de 10
        z_min_arrondi = int(zmin)
        z_max_arrondi = int(zmax)+1

        # Boucle sur les multiples de 10
        for z in range(int(z_min_arrondi), int(z_max_arrondi)):
            # Calcul de la position verticale dans la scène
            if zmax != zmin:
                y = MARGE_HAUT + plage_disponible * (1 - (z - zmin) / (zmax - zmin))
            else:
                y = self.scene.height() / 2

            # Texte de l'altitude
            txt = QGraphicsTextItem(f"{z}")
            txt.setFont(QFont('Arial', 7))
            txt.setPos(-3, y-7)  # à gauche de la scène
            self.scene.addItem(txt)

            # Optionnel : petit trait horizontal
            self.scene.addLine(MARGE_GAUCHE, y, self.scene.width(), y, QColor(235, 235, 235))

    def dessine_segment(self,d,list_z,list_x,list_y,distances_cumulees,distance_totale):
        plage_disponible = self.scene.height() - MARGE_BAS - MARGE_HAUT
        largeur_disponible = self.scene.width() - MARGE_GAUCHE - MARGE_DROITE
        zmin, zmax = self.getZminmax_allselection()
        for i in range(1, len(list_z)):
            # points SIG
            pt1 = QgsPoint(list_x[i - 1], list_y[i - 1], list_z[i - 1])
            pt2 = QgsPoint(list_x[i], list_y[i], list_z[i])

            pente_pc = self.calcul_pente(d,pt1, pt2)

            # positions graphiques
            x1 = MARGE_GAUCHE + (distances_cumulees[i - 1] / distance_totale) * largeur_disponible
            x2 = MARGE_GAUCHE + (distances_cumulees[i] / distance_totale) * largeur_disponible
            if zmax != zmin:
                y1 = MARGE_HAUT + plage_disponible * (1 - (list_z[i - 1] - zmin) / (zmax - zmin))
                y2 = MARGE_HAUT + plage_disponible * (1 - (list_z[i] - zmin) / (zmax - zmin))
            else:
                y1 = y2 = self.scene.height() / 2

            # couleur selon pente
            if pente_pc is not None and abs(pente_pc) > self.seuil_pente:
                color = QColor(255, 0, 0)  # rouge
                width = 3
            else:
                color = QColor(0, 0, 0)  # noir
                width = 1

            # dessin du segment
            seg_path = QPainterPath()
            seg_path.moveTo(x1, y1)
            seg_path.lineTo(x2, y2)

            segment_item = QGraphicsPathItem(seg_path)
            pen = segment_item.pen()
            pen.setColor(color)
            pen.setWidth(width)
            segment_item.setPen(pen)

            self.scene.addItem(segment_item)

            # affichage pente sur le segment
            if self.dlg.checkBox_pente.isChecked():
                if pente_pc is not None and pente_pc != 0:
                    txt = QGraphicsTextItem(f"{pente_pc:.1f} %")
                    txt.setFont(QFont('Arial', TAILLE_TXT_PENTE))
                    txt.setPos((x1 + x2) / 2, (y1 + y2) / 2 - 10)

                    # couleur de fond du texte de pente
                    # position du texte
                    txt_x = (x1 + x2) / 2
                    txt_y = (y1 + y2) / 2 - 10
                    txt.setPos(txt_x, txt_y)
                    rect = txt.boundingRect()
                    fond = QGraphicsRectItem(rect)
                    # fond.setBrush(QColor(255, 255, 100))  # couleur de fond
                    fond.setPen(QColor(0, 0, 0, 0))  # pas de bordure
                    fond.setPos(txt_x, txt_y)
                    self.scene.addItem(fond)
                    self.scene.addItem(txt)

    def dessine_profil(self, list_coord):
        # self.view.resetTransform()
        self.scene.clear()

        plage_disponible = self.scene.height() - MARGE_BAS - MARGE_HAUT
        largeur_disponible = self.scene.width() - MARGE_GAUCHE - MARGE_DROITE

        # récupération des coordonnées des tronçons sélectionnés
        # self.list_coord = self.get_coord_selection()
        self.list_x = list_coord["x"]
        self.list_y = list_coord["y"]
        self.list_z = list_coord["z"]

        # préparer la mesure de distance adaptée au CRS
        d = QgsDistanceArea()
        d.setSourceCrs(self.layer.crs(), QgsProject.instance().transformContext())
        if self.layer.crs().isGeographic():
            d.setEllipsoid(self.layer.crs().ellipsoidAcronym())

        # calcul de la distances cumulées entre points
        distances_cumulees = self.distance_cumulee(d,self.list_x, self.list_y)
        distance_totale = distances_cumulees[-1] or 1  # éviter division par zéro

        # min/max Z
        zmin, zmax = self.getZminmax_allselection()

        # DESSIN des graduations
        self.dessine_gradations_z(zmin, zmax)

        # ====================
        # DESSIN des segments et affiche pente sur segments
        # la couleur est en fonction de la pente
        self.dessine_segment(d,self.list_z, self.list_x, self.list_y,distances_cumulees,distance_totale)


        points_rouges = set()
        indice = 0
        for ligne in self.ligne_enchaine:
            points_rouges.add(indice)  # premier point du tronçon
            points_rouges.add(indice + len(ligne) - 1)  # dernier point du tronçon
            indice += len(ligne)

        # ==============
        # DESSIN des cercles et altitudes sur les sommets
        for i, z_point in enumerate(self.list_z):
            pos_x = MARGE_GAUCHE + (distances_cumulees[i] / distance_totale) * largeur_disponible
            if zmax != zmin:
                pos_z = MARGE_HAUT + plage_disponible * (1 - (z_point - zmin) / (zmax - zmin))
            else:
                pos_z = self.scene.height() / 2

            # définir le point cliqué pour ensuite le visualiser dans qgis
            qgs_point = QgsPointXY(self.list_x[i], self.list_y[i])
            # CERCLES ROUGE
            if i in points_rouges:
                cercle = CercleClickable(-TAILLE_CERCLE_EXTREMITE / 2, -TAILLE_CERCLE_EXTREMITE / 2,
                                        TAILLE_CERCLE_EXTREMITE, TAILLE_CERCLE_EXTREMITE, i,qgs_point,self)
                cercle.setBrush(QColor(255, 0, 0))
                cercle.setFlag(QGraphicsItem.ItemIgnoresTransformations, True)
                # force le cercle rouge à passer au-dessus des cercles verts
                cercle.setZValue(2)

            # CERCLES VERT
            else:
                cercle = CercleClickable(-TAILLE_CERCLE_INTER / 2, -TAILLE_CERCLE_INTER / 2,
                                     TAILLE_CERCLE_INTER, TAILLE_CERCLE_INTER, i,qgs_point, self)

                cercle.setBrush(QColor(0, 255, 0))
                # garde la taille des cercles fixes, Quel que soit le zoom
                cercle.setFlag(QGraphicsItem.ItemIgnoresTransformations, True)
                cercle.setZValue(1)

            cercle.setPos(pos_x, pos_z)
            self.scene.addItem(cercle)

            # ALTITUDE sur les sommets
            if self.dlg.checkBox_z.isChecked():
                altitude_text = QGraphicsTextItem(str(z_point))
                font = QFont('Arial', TAILLE_TXT_ALT, QFont.Bold)
                altitude_text.setFont(font)
                altitude_text.setPos(pos_x - 15, pos_z)
                altitude_text.setZValue(0)
                # le texte garde une taille fixe à l'écran malgré le zoom
                altitude_text.setFlag(QGraphicsItem.ItemIgnoresTransformations, True)
                self.scene.addItem(altitude_text)

        # self.view.setTransform(transform)
        self.dlg.label_nb_points.setText(f"Nb de points = {len(self.list_z)}")

    def unload(self):
        pass

    def creerscene(self):
        self.scene = QGraphicsScene(self.dlg)
        # self.layoutscene = QVBoxLayout()

        # Créer une vue pour afficher la scène
        self.view = QGraphicsView(self.scene,self.dlg)
        # déplacement dans la vue
        self.view.setDragMode(QGraphicsView.ScrollHandDrag)
        self.view.setStyleSheet("QGraphicsView { border: 3px solid black; }")
        self.view.setHorizontalScrollBarPolicy(ScrollBarAlwaysOff)
        self.view.setVerticalScrollBarPolicy(ScrollBarAlwaysOff)
        # self.dlg.setContentsMargins(0, 50, 0, 0)
        self.view.setSizePolicy(Expanding,Expanding)

        # Ajouter sur la dernière ligne
        last_row = self.dlg.gridLayout.rowCount()
        self.dlg.gridLayout.addWidget(self.view, last_row, 0, 1, self.dlg.gridLayout.columnCount())

        # self.dlg.gridLayout.addWidget(self.view)
        self.dlg.gridLayout.addWidget(self.view, 2, 0, 1, self.dlg.gridLayout.columnCount())

    # on redessine à chaque redimensionnement de la scene
    def on_resize(self, event):
        self.scene.setSceneRect(0, 0, self.view.viewport().width(), self.view.viewport().height())
        if self.list_coord:
            self.dessine_profil(self.list_coord)
        elif self.texte_scene:
            self.ecrire_dans_scene(self.texte_scene)

            event.accept()

    def mousemoveevent(self,event):
        if self.last_mouse_pos:
            # Calculer le déplacement de la souris
            delta = event.pos() - self.last_mouse_pos
            self.last_mouse_pos = event.pos()  # Mettre à jour la position de la souris

            # Déplacer la scène (ou vue) en fonction du mouvement de la souris
            self.view.translate(delta.x(), delta.y())
            event.accept()

    def mousereleaseevent(self,event):
        if event.button() == MiddleButton:
            self.last_mouse_pos = None  # Réinitialiser la position de la souris
            event.accept()

    def molette(self,event):
        scale = 1.5

        # position du curseur dans la scene
        cursor_pos = self.view.mapToScene(event.pos())
        # appliquer le zoom centré sur ce point
        if event.angleDelta().y() > 0:  # molette vers l’avant
            zoom = scale
        else:
            zoom = 1 / scale
        self.view.scale(zoom, zoom)
        # ajuster le centre pour que le point du curseur reste au même endroit
        new_center = cursor_pos
        self.view.centerOn(new_center)
        event.accept()

    def apropos(self):
        dlgAProposDe = QDialog()
        loadUi(os.path.dirname(__file__) + "/aproposde.ui", dlgAProposDe)
        dlgAProposDe.setWindowFlags(WindowStaysOnTopHint | WindowCloseButtonHint)
        dlgAProposDe.setWindowTitle(f"{TITRE}")
        dlgAProposDe.pushButtonAffichedoc.clicked.connect(afficheDoc)
        dlgAProposDe.exec()

    def sauve_position_dial(self):
        settings = QSettings(QSettings.NativeFormat, QSettings.UserScope,
                             "IGN", TITRE)
        settings.setValue("position", self.dlg.pos())
        settings.setValue("taille", self.dlg.size())
        settings.setValue("visible", self.dlg.isVisible())

    def restore_position_dial(self):
        settings = QSettings(QSettings.NativeFormat, QSettings.UserScope, "IGN", TITRE)
        pos = settings.value("position", type=QPoint)
        size = settings.value("taille", type=QSize)
        if pos is None:
            return
        screens = QApplication.screens()
        multi = len(screens) > 1
        # Vérifie si la position est sur un des écrans
        on_screen = any(screen.geometry().contains(pos) for screen in screens)
        if on_screen:
            self.dlg.move(pos)
            if size:
                self.dlg.resize(size)
        else:
            # Si un seul écran → replacer en haut-gauche
            if not multi:
                self.dlg.move(QPoint(0, 0))
            else:
                # Multi-écran mais position invalide → centrer sur écran principal
                primary = QApplication.primaryScreen().geometry()
                center = primary.center()
                self.dlg.move(center - self.dlg.rect().center())

    def fermeture_qgis(self):
        self.sauve_position_dial()

    def on_project_opened(self):
        settings = QSettings(QSettings.NativeFormat, QSettings.UserScope, "IGN", TITRE)
        visible = settings.value("visible", False, type=bool)

        if visible:
            self.run()

    def initGui(self):
        self.iface.projectRead.connect(self.on_project_opened)
        # événement fermeture de qgis
        QgsApplication.instance().aboutToQuit.connect(self.fermeture_qgis)

    def on_dialog_closed(self):
        self.sauve_position_dial()
        # déconnexion des signaux
        try:
            self.iface.mapCanvas().selectionChanged.disconnect(self.actualiserSelection)
        except TypeError:
            pass
        try:
            self.iface.currentLayerChanged.disconnect(self.actualiserSelection)
        except TypeError:
            pass
        # suppression des marqueurs
        for m in self.liste_markers:
            self.iface.mapCanvas().scene().removeItem(m)
        self.liste_markers.clear()
        self.dlg = None

    def run(self):
        if self.dlg is not None and self.dlg.isVisible():
            return
        if not is_projet_load():
            return

        self.dlg = AltibonneDialog()
        self.dlg.setWindowTitle(f"{TITRE}")

        # connection de la fermeture du dialogue
        self.dlg.finished.connect(self.on_dialog_closed)

        self.restore_position_dial()

        self.layer = self.iface.activeLayer()

        # si le layer est valide (couche en 3d)
        if not self.is_layer_valide():
            QMessageBox.warning(self.dlg, "Avertissement", f"La couche <span style = 'color:red'><b>{self.layer.name()}"
                                                           f" ({QgsWkbTypes.displayString(self.layer.wkbType())})</b></span> n'a pas de Z")
            return

        # si autre chose que linéaire
        if (QgsWkbTypes.displayString(self.layer.wkbType()) != "LineStringZ"
                and QgsWkbTypes.displayString(self.layer.wkbType()) != "MultiLineStringZ"):
            QMessageBox.warning(self.dlg, "Avertissement", f"La couche doit être de type linéaire")
            return

        # le plugin espace co ne remet pas le curseur par défaut
        # donc je le fais ici.
        while QApplication.overrideCursor() is not None:
            QApplication.restoreOverrideCursor()

        self.dlg.label_nb_points.setText(f"Nb de points = {0}")
        self.dlg.label_warning.setText("")

        self.creerscene()
        # événement actualisation selection
        self.iface.mapCanvas().selectionChanged.connect(self.actualiserSelection)

        # delta z
        # nombre compris entre -100 et 100 avec 1 décimale
        regex = QRegularExpression(r"^(-?(100(\.0{1,2})?|(\d{1,2})(\.\d{1,2})?))|(0(\.0{1,2})?)$ ")
        validator = QRegularExpressionValidator(regex, self.dlg)
        self.dlg.lineEdit_valZ.setValidator(validator)
        self.dlg.lineEdit_valZ.setText("0")

        # z interpolé
        # nombre compris entre 0 et 4000 avec 1 décimale
        regex = QRegularExpression(r"^(?:0(?:\.\d)?|[1-9]\d{0,2}(?:\.\d)?|[1-3]\d{3}(?:\.\d)?|4000(?:\.0)?)$")
        validator = QRegularExpressionValidator(regex, self.dlg)
        self.dlg.lineEditZInterpole.setValidator(validator)

        # pente
        # nombre compris entre 1 et 90 avec 1 décimale
        regex = QRegularExpression(r"^(?:[1-9](?:\.\d)?|[1-8]\d(?:\.\d)?|90(?:\.0)?)$")
        validator = QRegularExpressionValidator(regex, self.dlg)
        self.dlg.lineEdit_seuil_pente.setValidator(validator)
        self.dlg.lineEdit_seuil_pente.setText("15")
        self.seuil_pente = int(self.dlg.lineEdit_seuil_pente.text())

        # a propos...
        self.dlg.pushButtonApropos.clicked.connect(self.apropos)

        # événement bouton
        self.dlg.pushButton_actualiser.clicked.connect(self.actualiser_seuil)
        self.dlg.pushButton_actualiser.setStyleSheet(CUSTOM_WIDGETS[1])
        self.dlg.pushButtonUpDown.clicked.connect(self.changeZentite)
        self.dlg.pushButtonUpDown.setStyleSheet(CUSTOM_WIDGETS[0])
        self.dlg.pushButtonChangeZpoint.clicked.connect(self.changeZpoint)
        self.dlg.pushButtonChangeZpoint.setStyleSheet(CUSTOM_WIDGETS[0])

        self.iface.currentLayerChanged.connect(self.actualiserSelection)

        # événement du lineedit
        self.dlg.lineEdit_valZ.textEdited.connect(lambda :self.is_saisie_valide(self.dlg.lineEdit_valZ,self.dlg.pushButtonUpDown))
        self.dlg.lineEditZInterpole.textEdited.connect(lambda: self.is_saisie_valide(self.dlg.lineEditZInterpole,self.dlg.pushButtonChangeZpoint))

        # signal des checkbox
        self.dlg.checkBox_z.stateChanged.connect(lambda :self.actualiserSelection(False))
        self.dlg.checkBox_pente.stateChanged.connect(lambda :self.actualiserSelection(False))

        # aspect des line edit
        self.dlg.lineEdit_valZ.setStyleSheet(CUSTOM_WIDGETS[2])
        self.dlg.lineEditZpoint.setStyleSheet(CUSTOM_WIDGETS[2])
        self.dlg.lineEditZInterpole.setStyleSheet(CUSTOM_WIDGETS[2])
        self.dlg.lineEdit_seuil_pente.setStyleSheet(CUSTOM_WIDGETS[2])

        # aspect dialog et view
        self.dlg.setStyleSheet(CUSTOM_WIDGETS[3])
        self.view.setStyleSheet(CUSTOM_WIDGETS[4])

        self.dlg.resizeEvent = self.on_resize
        self.dlg.mouseMoveEvent = self.mousemoveevent
        self.dlg.mouseReleaseEvent = self.mousereleaseevent
        self.dlg.wheelEvent = self.molette

        self.dlg.setParent(self.iface.mainWindow())
        self.dlg.setWindowFlags(Dialog | WindowTitleHint | WindowCloseButtonHint)
        # show the dialog

        self.dlg.show()
        self.actualiserSelection()

        # Run the dialog event loop
        # result = self.dlg.exec()
        # if result == QDialog.Rejected:
        #     self.sauve_position_dial()
        #     # on déconnecte le signal en quittant
        #     try:
        #         self.iface.mapCanvas().selectionChanged.disconnect(self.actualiserSelection)
        #     except TypeError:
        #         pass  # aucune connexion existante
        #     # suppression de tous les marqueurs (pointer le point cliqué) lorsqu'on quitte
        #     for m in self.liste_markers:
        #         self.iface.mapCanvas().scene().removeItem(m)
        #     self.liste_markers.clear()

